### ISSUE TITLE
Guide !

### ISSUE THREAD

**Issue by Abhinav1217** [algent-al/solus-extra-repo#2]
Hi, I know this repo is for  your private usage, But there are few things I want to get for my system too. I am familiar with using pspec.xml and action.py for building eopkg but I am not familiar with using package.yml .

 Please provide some instructions on how to build .eopkg file from package.yml .

**Comment by algent-al** [comment]
Hi! There are some old videos on YouTube and they are still valid.
1. https://www.youtube.com/watch?v=rlPnHjUBpJ8
2. https://www.youtube.com/watch?v=xK-1726MWqQ
3. https://www.youtube.com/watch?v=c_vIg3ep3YE

Check the docs too: https://help.getsol.us/docs/packaging
